//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryCarrito.web.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DIRECCION
    {
        public int DIR_ID { get; set; }
        public Nullable<int> CLI_ID { get; set; }
        public string CLI_IDENTIFICACION { get; set; }
        public string DIR_PRINCIPAL { get; set; }
        public string DIR_SECUNDARIA { get; set; }
        public string DIR_NUMERACION { get; set; }
        public string DIR_REFERENCIA { get; set; }
        public string DIR_STATUS { get; set; }
        public string DIR_CODIGOPOSTAL { get; set; }
        public Nullable<System.DateTime> DIR_FECHACREACION { get; set; }
    
        public virtual TBL_CLIENTE TBL_CLIENTE { get; set; }
    }
}
