//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryCarrito.web.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CATEGORIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CATEGORIA()
        {
            this.TBL_PRODUCTO = new HashSet<TBL_PRODUCTO>();
        }
    
        public int CAT_ID { get; set; }
        public string CAT_STATUS { get; set; }
        public Nullable<System.DateTime> CAT_FECHACREACION { get; set; }
        public string CAT_NOMBRE { get; set; }
        public string CAT_DESCRIPCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRODUCTO> TBL_PRODUCTO { get; set; }
    }
}
