//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryCarrito.web.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLEPEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DETALLEPEDIDO()
        {
            this.TBL_DETALLEIMPRESION = new HashSet<TBL_DETALLEIMPRESION>();
        }
    
        public int DEP_CODIGO { get; set; }
        public Nullable<int> PRO_ID { get; set; }
        public string PRO_CODIGO { get; set; }
        public Nullable<int> PED_ID { get; set; }
        public Nullable<System.DateTime> PED_FECHA { get; set; }
        public string DEP_CANTIDAD { get; set; }
        public string DEP_DESCRIPCION { get; set; }
        public string DEP_PRECIOUNITARIO { get; set; }
        public string DEP_PRECIOTOTAL { get; set; }
        public string DEP_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DETALLEIMPRESION> TBL_DETALLEIMPRESION { get; set; }
        public virtual TBL_PEDIDO TBL_PEDIDO { get; set; }
        public virtual TBL_PRODUCTO TBL_PRODUCTO { get; set; }
    }
}
