//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryCarrito.web.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        public int USU_ID { get; set; }
        public Nullable<int> ROL_ID { get; set; }
        public string USU_USUARIO { get; set; }
        public string USU_CLAVE { get; set; }
        public string USU_STATUS { get; set; }
        public Nullable<System.DateTime> USU_FECHACREACION { get; set; }
    
        public virtual TBL_ROL TBL_ROL { get; set; }
    }
}
